### PR TITLE
Adjusting date time text to match image size

### PR DESCRIPTION
**Pull request by ZachHoppinen**
Hello,

Feel free to close if this isn't helpful but when I use this great package with large xarray dataarrays the date text in the corner get very small and illegible. This push:

 - Sets an initial text size of 6 pt
 - Checks if the resulting bounding box will be 10% of image width
 - If it is smaller it increments to the next larger font size until the date time text fills in 10% of image

Credit to this slack exchange answer: https://stackoverflow.com/questions/4902198/pil-how-to-scale-text-size-in-relation-to-the-size-of-the-image

One weird thing I found was the background box was too short vertically after these changes so I added a 1.6x multiplier to the height to make the text work but I suspect I may just be missing something there.

Cheers!
Zach

### CODE REVIEW

**Comment by ZachHoppinen** [comment]
Just noticed this may resolve #18 to some extent as well.

**Review by gjoseph92 — COMMENTED** [review]
@ZachHoppinen thanks so much for working on this! The tiny font has always bothered me too. When I wrote all this originally, the built-in font with Pillow didn't support different sizes, but it seems that as of 10.1, the default font has changed and we can now do this. So thanks for looking into it.

I've played around with this a bit and am pushing a few changes:
- actually requiring Pillow 10.1 (otherwise passing `size=` would throw an error with older versions)
- exposing the size as an argument (both as a fraction, like you've done, and an absolute font size)
- figuring out why the text wasn't getting fully covered, instead of the 1.6x height workaround
- updating the docs with new examples showing how this looks, and how to use it

**Comment by gjoseph92** [comment]
@ZachHoppinen I'll leave this for you to test out on your data, but I think it's good to go, so once you confirm I'll merge and cut a release!

**Comment by gjoseph92** [comment]
Great to hear! Thanks for the contribution and figuring out the core change!

**Review by gjoseph92 — APPROVED** [review]

**Pull request merged**
